name: firebase-deploy-hosting

on:
  push:
    branches:
      - master

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout master
        uses: actions/checkout@master
      - name: install dependencies
        run: npm install
      - name: build
        run: npm run build
        env: 
          VERSION: $(git rev-parse --short HEAD)
      - name: archive build
        uses: actions/upload-artifact@master
        with:
          name: build
          path: build
  deploy:
    name: deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout master
        uses: actions/checkout@master
      - name: download build
        uses: actions/download-artifact@master
        with:
          name: build
      - name: deploy
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting --message $(git rev-parse --short HEAD)
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
